# Generated by Django 5.0.9 on 2024-12-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProviderView',
            fields=[
                ('cp_id', models.IntegerField(db_column='ClientID', primary_key=True, serialize=False)),
                ('provider_id', models.IntegerField(db_column='ProviderID')),
                ('seeker_id', models.IntegerField(db_column='SeekerID')),
                ('provider_name', models.CharField(db_column='ProviderName', max_length=255)),
                ('provider_email', models.EmailField(db_column='ProviderEmail', max_length=254)),
                ('relationship', models.CharField(db_column='Relationship', max_length=255)),
                ('status', models.CharField(db_column='Status', max_length=50)),
                ('user_id', models.IntegerField(db_column='UserID')),
            ],
            options={
                'db_table': 'user_provider_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSeekerView',
            fields=[
                ('cp_id', models.IntegerField(db_column='ClientID', primary_key=True, serialize=False)),
                ('provider_id', models.IntegerField(db_column='ProviderID')),
                ('seeker_id', models.IntegerField(db_column='SeekerID')),
                ('seeker_name', models.CharField(db_column='SeekerName', max_length=255)),
                ('seeker_email', models.EmailField(db_column='SeekerEmail', max_length=254)),
                ('relationship', models.CharField(db_column='Relationship', max_length=255)),
                ('status', models.CharField(db_column='Status', max_length=50)),
                ('user_id', models.IntegerField(db_column='UserID')),
            ],
            options={
                'db_table': 'user_seeker_view',
                'managed': False,
            },
        ),
    ]
