# Generated by Django 5.0.9 on 2024-12-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliPr',
            fields=[
                ('cp_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('seeker_id', models.IntegerField()),
                ('seeker_name', models.CharField(max_length=255)),
                ('seeker_email', models.EmailField(max_length=254)),
                ('provider_id', models.IntegerField()),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'CliPr',
            },
        ),
        migrations.RemoveField(
            model_name='superuser_unique_url',
            name='superuser_id',
        ),
        migrations.AlterField(
            model_name='seeker',
            name='seeker_last_name',
            field=models.CharField(default='Jafri', max_length=255),
        ),
        migrations.DeleteModel(
            name='Provider_Unique_url',
        ),
        migrations.DeleteModel(
            name='Superuser_Unique_url',
        ),
    ]
