# Generated by Django 5.0.9 on 2024-12-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0002_userproviderview_userseekerview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullRatingDataView',
            fields=[
                ('cp_id', models.IntegerField(db_column='ClientID', primary_key=True, serialize=False)),
                ('client_name', models.CharField(db_column='ClientName', max_length=255)),
                ('project_name', models.CharField(db_column='ProjectName', max_length=255)),
                ('seeker_name', models.CharField(db_column='SeekerName', max_length=255)),
                ('seeker_email', models.EmailField(db_column='SeekerEmail', max_length=254)),
                ('provider_email', models.EmailField(db_column='ProviderEmail', max_length=254)),
                ('relationship', models.CharField(db_column='Relationship', max_length=255)),
                ('question_text', models.TextField(db_column='QuestionText')),
                ('competency', models.CharField(db_column='Competency', max_length=255)),
                ('feedback_value', models.FloatField(db_column='FeedbackValue')),
            ],
            options={
                'db_table': 'full_rating_data_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenQuestionView',
            fields=[
                ('cp_id', models.IntegerField(db_column='ClientID', primary_key=True, serialize=False)),
                ('client_name', models.CharField(db_column='ClientName', max_length=255)),
                ('project_name', models.CharField(db_column='ProjectName', max_length=255)),
                ('seeker_name', models.CharField(db_column='SeekerName', max_length=255)),
                ('seeker_email', models.EmailField(db_column='SeekerEmail', max_length=254)),
                ('provider_email', models.EmailField(db_column='ProviderEmail', max_length=254)),
                ('relationship', models.CharField(db_column='Relationship', max_length=255)),
                ('question_text', models.TextField(db_column='QuestionText')),
                ('feedback_text', models.TextField(db_column='FeedbackText')),
            ],
            options={
                'db_table': 'open_question_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OptimumMinimumCriteriaView',
            fields=[
                ('cp_id', models.IntegerField(db_column='ClientID', primary_key=True, serialize=False)),
                ('seeker_id', models.IntegerField(db_column='SeekerID')),
                ('optimum_criteria', models.CharField(db_column='Optimum_Criteria', max_length=255)),
                ('minimum_criteria', models.CharField(db_column='Minimum_Criteria', max_length=255)),
            ],
            options={
                'db_table': 'optimum_minimum_criteria_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniqueSeekerProviderView',
            fields=[
                ('cp_id', models.IntegerField(db_column='ClientID', primary_key=True, serialize=False)),
                ('provider_id', models.IntegerField(db_column='ProviderID')),
                ('seeker_id', models.IntegerField(db_column='SeekerID')),
                ('relationship', models.CharField(db_column='Relationship', max_length=255)),
            ],
            options={
                'db_table': 'unique_seeker_provider_view',
                'managed': False,
            },
        ),
    ]
