# Generated by Django 5.0.9 on 2024-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0002_userproviderview_userseekerview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueSeekerProviderView',
            fields=[
                ('cp_id', models.IntegerField(db_column='ClientID', primary_key=True, serialize=False)),
                ('provider_id', models.IntegerField(db_column='ProviderID')),
                ('seeker_id', models.IntegerField(db_column='SeekerID')),
                ('relationship', models.CharField(db_column='Relationship', max_length=255)),
            ],
            options={
                'db_table': 'unique_seeker_provider_view',
                'managed': False,
            },
        ),
    ]
