# Generated by Django 5.0.9 on 2024-12-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0003_providerurl_superuserurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerurl',
            old_name='cp_id',
            new_name='cp',
        ),
        migrations.RenameField(
            model_name='superuserurl',
            old_name='cp_id',
            new_name='cp',
        ),
    ]
