# Generated by Django 5.0.9 on 2024-12-05 05:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0004_rename_cp_id_providerurl_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerurl',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='superuserurl',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
