# Generated by Django 5.0.9 on 2024-12-05 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0005_providerurl_unique_id_superuserurl_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerurl',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='superuserurl',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
