# Generated by Django 5.0.9 on 2024-12-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0006_alter_providerurl_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clipr',
            options={'managed': False},
        ),
    ]
