# Generated by Django 5.1.2 on 2024-11-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeedbackProvider',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
