# Generated by Django 5.1.2 on 2024-11-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WrittenAnswer',
        ),
    ]
